version: '2'
services:
    loyality-app:
        image: loyality
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://loyality-mysql:3306/loyality?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    loyality-mysql:
        extends:
            file: mysql.yml
            service: loyality-mysql
